### ISSUE TITLE
Feature request: Optionally specify a time or duration to delay execution of a task

### ISSUE THREAD

**Issue by mikestefanello** [maragudk/goqite#49]
I thought it would be useful to be able to specify either a specific date and time or duration to delay executing a given task.

**Comment by markuswustenberg** [comment]
A `goqite.Message` already has this, but true it's not reflected in the jobs abstraction. I haven't had a need yet. I'll think about it. 😊

https://pkg.go.dev/github.com/maragudk/goqite@v0.2.3#Message
